# Generated by Django 4.1.4 on 2022-12-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_vrew',
            new_name='delivery_crew',
        ),
    ]
