# Generated by Django 4.1.4 on 2022-12-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_rename_delivery_vrew_order_delivery_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
